# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semaphore_app', '0002_auto_20170603_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instance',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='pingresults',
            old_name='user_id',
            new_name='user',
        ),
    ]
