# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 01:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    dependencies = [
        ('semaphore_app', '0003_auto_20170603_2022'),
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='InstancesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('data', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
    ]
