# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semaphore_app', '0004_instanceslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pingresults',
            name='instance',
            field=models.IntegerField(),
        ),
    ]
